services:
  terraform_workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PLURALITH_API_KEY: ${PLURALITH_API_KEY}
        PLURALITH_VERSION: ${PLURALITH_VERSION}
    container_name: terraform_workspace
    hostname: terraform_workspace
    shm_size: '1gb'
    volumes:
      - ./:/workspace:cached
      - $HOME/.aws/:/root/.aws/:cached
    environment:
      TZ: Asia/Tokyo
    tty: true
