version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.${region}.amazonaws.com

  build:
    commands:
      - docker build --target prod -t ${repository_url}:${image_tag} .

  post_build:
    commands:
      - docker push ${repository_url}:${image_tag}
      - aws lambda update-function-code --function-name ${function_name} --image-uri ${repository_url}:${image_tag}
      - cp -r ./docs documents

artifacts:
  files:
    - "**/*"
  base-directory: documents
