version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.${region}.amazonaws.com

  build:
    on-failure: ABORT
    commands:
      - docker build --target prod -t ${repository_url}:${image_tag} .

  post_build:
    on-failure: ABORT
    commands:
      - docker push ${repository_url}:${image_tag}

artifacts:
  files:
    - "**/*"
  base-directory: documents
